# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-Copy
version:      1.23
version_from: lib/HTML/Copy.pm
installdirs:  site
requires:
    Class::Accessor:               0
    HTML::Parser:                  3.4
    HTTP::Headers:                 0
    Test::More:                    0
    URI:                           0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
