# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-Copy
version:      1.1.1
version_from: lib/HTML/Copy.pm
installdirs:  site
requires:
    HTML::Parser:                  3.4
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
